/**
 * Auto-generated by temp/desktop_i18n.py — keep trilingual chrome in sync.
 * Used by main.js for native dialogs and update state messages.
 */
const DESKTOP_LABELS = Object.freeze({
  desktop_update_invalid_version: { zh: "当前桌面端版本不是有效的语义化版本，无法检查更新。", en: "The current desktop version is not a valid semver release; cannot check for updates.", ko: "현재 데스크톱 버전이 유효한 시맨틱 버전이 아니어서 업데이트를 확인할 수 없습니다." },
  desktop_update_invalid_release_metadata: { zh: "GitHub Release 未返回可识别的语义化版本标签。", en: "GitHub Release did not return a recognizable semver tag.", ko: "GitHub Release에서 인식 가능한 시맨틱 버전 태그를 받지 못했습니다." },
  desktop_update_version_compare_failed: { zh: "版本比较失败，无法判断是否存在可用更新。", en: "Version comparison failed; cannot determine whether an update is available.", ko: "버전 비교에 실패하여 사용 가능한 업데이트가 있는지 확인할 수 없습니다." },
  desktop_update_new_version_available: { zh: "发现新版本 {version}，可前往 GitHub Releases 下载更新。", en: "New version {version} is available. Open GitHub Releases to download the update.", ko: "새 버전 {version}이(가) 있습니다. GitHub Releases에서 업데이트를 다운로드하세요." },
  desktop_update_up_to_date: { zh: "当前桌面端已是最新版本。", en: "The desktop client is already up to date.", ko: "데스크톱 클라이언트가 이미 최신 버전입니다." },
  desktop_update_dialog_title: { zh: "发现新版本", en: "New version available", ko: "새 버전 사용 가능" },
  desktop_update_dialog_message: { zh: "检测到桌面端新版本 {version}", en: "A new desktop version {version} is available", ko: "새 데스크톱 버전 {version}이(가) 있습니다" },
  desktop_update_dialog_detail: { zh: "当前版本 {current}。新版本将跳转到 GitHub Releases 下载页，不会静默下载或自动安装。", en: "Current version {current}. The new release opens the GitHub Releases page; nothing is downloaded or installed silently.", ko: "현재 버전 {current}. 새 버전은 GitHub Releases 페이지로 이동하며, 조용히 다운로드하거나 자동 설치하지 않습니다." },
  desktop_update_dialog_button_later: { zh: "稍后", en: "Later", ko: "나중에" },
  desktop_update_dialog_button_download: { zh: "前往下载", en: "Open download page", ko: "다운로드 페이지 열기" },
  desktop_update_install_unsupported: { zh: "当前运行模式不支持自动安装更新。", en: "Auto-install is not supported in the current run mode.", ko: "현재 실행 모드에서는 자동 설치가 지원되지 않습니다." },
  desktop_update_not_downloaded: { zh: "更新尚未下载完成，无法自动安装。", en: "The update has not finished downloading, so it cannot be installed automatically.", ko: "업데이트가 아직 다운로드 완료되지 않아 자동으로 설치할 수 없습니다." },
  desktop_update_installing: { zh: "正在重启并安装更新...", en: "Restarting and installing the update...", ko: "업데이트를 재시작하고 설치하는 중..." },
  desktop_update_prepare_failed: { zh: "更新安装准备失败：{error}", en: "Failed to prepare the update: {error}", ko: "업데이트 준비 실패: {error}" },
  desktop_update_install_failed_short: { zh: "更新安装失败：{error}。可先保存草稿并前往下载页，或稍后重试。", en: "Update installation failed: {error}. Save your draft and open the release page, or try again later.", ko: "업데이트 설치 실패: {error}. 초안을 저장하고 릴리스 페이지를 열거나 나중에 다시 시도하세요." },
  desktop_update_downloaded_dialog_title: { zh: "更新已下载", en: "Update downloaded", ko: "업데이트 다운로드 완료" },
  desktop_update_downloaded_dialog_message: { zh: "桌面端新版本 {version} 已下载", en: "The new desktop version {version} has been downloaded", ko: "새 데스크톱 버전 {version}이(가) 다운로드되었습니다" },
  desktop_update_downloaded_dialog_detail: { zh: "重启应用后会自动完成安装。未保存的设置草稿请先保存。", en: "The install will finish automatically after the app restarts. Save any unsaved draft settings first.", ko: "앱을 재시작하면 설치가 자동으로 완료됩니다. 저장하지 않은 설정 초안을 먼저 저장하세요." },
  desktop_update_downloaded_button_later: { zh: "稍后", en: "Later", ko: "나중에" },
  desktop_update_downloaded_button_install: { zh: "立即重启安装", en: "Restart and install now", ko: "지금 재시작하여 설치" },
  desktop_update_autocheck_unsupported: { zh: "当前平台不支持自动安装更新。", en: "Auto-install is not supported on this platform.", ko: "이 플랫폼에서는 자동 설치가 지원되지 않습니다." },
  desktop_update_checking: { zh: "正在检查桌面端更新...", en: "Checking for desktop updates...", ko: "데스크톱 업데이트 확인 중..." },
  desktop_update_checking_background: { zh: "正在后台检查桌面端更新...", en: "Checking for desktop updates in the background...", ko: "백그라운드에서 데스크톱 업데이트 확인 중..." },
  desktop_update_check_failed: { zh: "检查更新失败：{error}", en: "Update check failed: {error}", ko: "업데이트 확인 실패: {error}" },
  desktop_update_downloading: { zh: "正在下载桌面端更新...", en: "Downloading the desktop update...", ko: "데스크톱 업데이트 다운로드 중..." },
  desktop_update_downloading_percent: { zh: "正在下载桌面端更新（{percent}%）...", en: "Downloading the desktop update ({percent}%)...", ko: "데스크톱 업데이트 다운로드 중 ({percent}%)..." },
  desktop_update_downloaded_new_version: { zh: "新版本 {version} 已下载，可重启应用完成安装。", en: "Version {version} has been downloaded. Restart the app to finish installing.", ko: "버전 {version}이(가) 다운로드되었습니다. 앱을 재시작하여 설치를 완료하세요." },
  desktop_update_downloaded_ready: { zh: "新版本已下载，可重启应用完成安装。", en: "The new version has been downloaded. Restart the app to finish installing.", ko: "새 버전이 다운로드되었습니다. 앱을 재시작하여 설치를 완료하세요." },
  desktop_update_downloading_background: { zh: "发现新版本 {version}，正在后台下载更新...", en: "New version {version} is available; downloading in the background...", ko: "새 버전 {version}이(가) 발견되었습니다. 백그라운드에서 다운로드 중..." },
  desktop_update_autorun_failed: { zh: "自动更新失败：{error}", en: "Auto-update failed: {error}", ko: "자동 업데이트 실패: {error}" },
  desktop_update_recovery_prompt: { zh: "上次更新安装未完成或恢复运行时文件失败，已保留备份目录 {backupRoot}，请确认后手动恢复并重启应用。明细：{details}", en: "The previous update install did not finish or the runtime files failed to restore. A backup directory at {backupRoot} has been kept; review it, restore manually, and restart the app. Details: {details}", ko: "이전 업데이트 설치가 완료되지 않았거나 런타임 파일 복원에 실패했습니다. {backupRoot}에 백업 디렉터리가 보관되어 있습니다. 확인 후 수동으로 복원하고 앱을 재시작하세요. 세부 정보: {details}" },
  desktop_update_recovery_default_current: { zh: "当前版本", en: "Current version", ko: "현재 버전" },
  desktop_update_recovery_default_latest: { zh: "最新版本", en: "Latest version", ko: "최신 버전" },
});

function resolveDesktopLanguage() {
  // 1. Honor explicit override env var (desktop ops).
  const explicit = process.env.DSA_DESKTOP_LANGUAGE;
  if (explicit && Object.prototype.hasOwnProperty.call(DESKTOP_LABELS.desktop_update_checking, explicit)) {
    return explicit;
  }
  // 2. Detect from LANG / LC_ALL / LANGUAGE.
  const envLocale = (process.env.LC_ALL || process.env.LANG || process.env.LANGUAGE || '').toLowerCase();
  if (envLocale.startsWith('ko')) return 'ko';
  if (envLocale.startsWith('en')) return 'en';
  if (envLocale.startsWith('zh')) return 'zh';
  // 3. Default to English.
  return 'en';
}

const DESKTOP_LANGUAGE = resolveDesktopLanguage();

function desktopT(key, vars = {}) {
  const entry = DESKTOP_LABELS[key];
  if (!entry) {
    return key;
  }
  const template = entry[DESKTOP_LANGUAGE] || entry.en || entry.zh || key;
  return template.replace(/\{(\w+)\}/g, (_match, name) => {
    return Object.prototype.hasOwnProperty.call(vars, name) ? String(vars[name]) : `{${name}}`;
  });
}

module.exports = {
  DESKTOP_LABELS,
  DESKTOP_LANGUAGE,
  desktopT,
  resolveDesktopLanguage,
};
