name: analisis-diario-de-acciones

services:
  analizador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analizador-acciones
    restart: unless-stopped
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - WEBUI_HOST=0.0.0.0
    volumes:
      - datos_app:/app/data
      - registros_app:/app/logs
      - reportes_app:/app/reports
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  datos_app:
  registros_app:
  reportes_app:
